server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/je1907_orders?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    password: 1234
    username: root
    driver: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: eurekaclient-provider
eureka:
  instance:
    prefer-ip-address: true  #设置显示ip
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka
      #这里说eurekaserver运行起来后的地址
mybatis:
  type-aliases-package: com.tu.pojo
  mapper-locations: classpath:mapper/*.xml